--- 
- !ruby/object:SystemSettings 
  attributes: 
    session_timeout: "7200"
    menu_depth: "3"
    permission_denied_page_id: "4"
    site_default_page_id: "1"
    id: "1"
    not_found_page_id: "3"
    default_markup_style_id: "1"
    public_role_id: "1"
    site_name: Expertiza
    footer_message: <a href="http://research.csc.ncsu.edu/efg/expertiza/papers">Expertiza</a>
    site_subtitle: Reusable learning objects through peer review
    session_expired_page_id: "2"
  attributes_cache: {}

